services:
  postgres:
    image: postgres:16-alpine
    container_name: wallet-db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '${DATABASE_PORT}:5432'
    volumes:
      - wallet-data:/var/lib/postgres/data

  wallet:
    build: .
    container_name: wallet
    depends_on:
      - postgres
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      SERVER_PORT: ${SERVER_PORT}
      CLIENT_URL: ${CLIENT_URL}
    ports:
      - "8080:${SERVER_PORT}"

volumes:
  wallet-data:
    driver: local