logging:
  level:
    root: INFO
  file:
    name: ${user.dir}/logs/java.log
server:
  port: 8080

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: db.changelog/changelog.xml
    enabled: true